security:
    enable_authenticator_manager: true
    hide_user_not_found: true
    password_hashers:
        DatingLibre\AppBundle\Entity\User:
            algorithm: auto
    providers:
        app_user_provider:
            entity:
                class: DatingLibre\AppBundle\Entity\User
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            form_login:
                login_path: /
                check_path: /
                username_parameter: 'email'
                password_parameter: 'password'
                enable_csrf: true
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /
                secure: true
                samesite: strict
            logout:
                path: logout
                target: /?logout=success
    access_control:
        - { path: ^/ccbill, roles: PUBLIC_ACCESS, ips: [ 64.38.212.1/24, 64.38.215.1/24, 64.38.240.1/24, 64.38.241.1/24 ] }
        - { path: ^/moderator, roles: [ROLE_ADMIN, ROLE_MODERATOR]}
        - { path: ^/admin, roles: [ROLE_ADMIN]}
        - { path: ^/$, roles: PUBLIC_ACCESS }
        - { path: ^/register, roles: PUBLIC_ACCESS }
        - { path: ^/token, roles: PUBLIC_ACCESS }
        - { path: ^/user/password/reset$, roles: PUBLIC_ACCESS }
        - { path: ^/user/password/update$, roles: PUBLIC_ACCESS }
        - { path: ^/, roles: ROLE_USER }